extends Node

# ! Comments prefixed with "!" mean they are extra info. Comments without them
# ! should be kept because they give your mod structure and make it easier to
# ! read by other modders
# ! Comments with "?" should be replaced by you with the appropriate information

# ! This template file is statically typed. You don't have to do that, but it can help avoid bugs
# ! You can learn more about static typing in the docs
# ! https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/static_typing.html

# ? Brief overview of what your mod does...

const MOD_DIR := "buckstrom-royalconvergence" # Name of the directory that this file is in
const LOG_NAME := "buckstrom-royalconvergence:Main" # Full ID of the mod (AuthorName-ModName)

var mod_dir_path := ""
var extensions_dir_path := ""
var translations_dir_path := ""

const EXTENSION_SCRIPT_PATHS : Array[String] = [
	"res://mods-unpacked/buckstrom-royalconvergence/extensions/objects/global/globals.gd",
]

const OVERWRITE_FILE_PATHS : Dictionary[String, String] = {
	"res://objects/battle/battle_resources/gag_loadouts/gag_tracks/trap.tres": "res://mods-unpacked/buckstrom-royalconvergence/overwrites/trap.tres"
}

var overwrites: Array

const HOOK_SCRIPT_PATHS : Dictionary[String, String] = {
	"res://objects/battle/battle_ui/gag_track.gd": "res://mods-unpacked/buckstrom-royalconvergence/extensions/objects/battle/battle_ui/gag_track.gd",
	"res://objects/battle/battle_ui/item_panel.gd": "res://mods-unpacked/buckstrom-royalconvergence/extensions/objects/battle/battle_ui/item_panel.gd",
}

var util_paths: Dictionary[String, String] = {
	"SpinUtil": "res://mods-unpacked/buckstrom-royalconvergence/spin/spin_util.gd"
}

# ! your _ready func.
func _init() -> void:
	ModLoaderLog.info("Init", LOG_NAME)
	mod_dir_path = ModLoaderMod.get_unpacked_dir().path_join(MOD_DIR)

	# Add extensions
	install_script_extensions()
	install_script_hook_files()
	
	_add_global_class()
	_add_child_class()

	# Add translations
	#add_translations()


func install_script_extensions() -> void:
	# ! any script extensions should go in this directory, and should follow the same directory structure as vanilla
	extensions_dir_path = mod_dir_path.path_join("extensions")
	for path in EXTENSION_SCRIPT_PATHS:
		ModLoaderMod.install_script_extension(path)
	for path in OVERWRITE_FILE_PATHS.keys():
		var overwrite := load(OVERWRITE_FILE_PATHS[path])
		overwrite.take_over_path(path)
		overwrites.append(overwrite)

	# ? Brief description/reason behind this edit of vanilla code...
	#ModLoaderMod.install_script_extension(extensions_dir_path.path_join("main.gd"))
	#ModLoaderMod.install_script_extension(ext_dir + "entities/units/player/player.gd") # ! Note that this file does not exist in this example mod

	# ! Add extensions (longform version of the above)
	#ModLoaderMod.install_script_extension("res://mods-unpacked/AuthorName-ModName/extensions/main.gd")
	#ModLoaderMod.install_script_extension("res://mods-unpacked/AuthorName-ModName/extensions/entities/units/player/player.gd")


func install_script_hook_files() -> void:
	for path in HOOK_SCRIPT_PATHS.keys():
		ModLoaderMod.install_script_hooks(path, HOOK_SCRIPT_PATHS[path])
	#extensions_dir_path = mod_dir_path.path_join("extensions")
	#ModLoaderMod.install_script_hooks("res://main.gd", extensions_dir_path.path_join("main.gd"))


func add_translations() -> void:
	# ! Place all of your translation files into this directory
	translations_dir_path = mod_dir_path.path_join("translations")

	# ! Load translations for your mod, if you need them.
	# ! Add translations by adding a CSV called "modname.csv" into the "translations" directory.
	# ! Godot will automatically generate a ".translation" file, eg "modname.en.translation".
	# ! Note that in this example, only the file called "modname.csv" is custom;
	# ! any other files in the "translations" directory were automatically generated by Godot
	ModLoaderMod.add_translation(translations_dir_path.path_join("modname.en.position"))

func _add_global_class() -> void:
	var global_instance = load("res://mods-unpacked/buckstrom-royalconvergence/rc_global.gd").new()
	global_instance.name = "RCglobal"
	add_child(global_instance)

func _add_child_class() -> void:
	for util in util_paths.keys():
		var instance = load(util_paths[util]).new()
		instance.name = util
		add_child(instance)

func _ready() -> void:
	ModLoaderLog.info("Ready", LOG_NAME)

	ModLoaderLog.info("Attempting to inject character.", LOG_NAME)
	var character_resources = [
		"flippy_2",
		"the_warden"
	]
	for resource in character_resources:
		var character_path: String = ModLoaderMod.get_unpacked_dir().path_join(MOD_DIR).path_join("%s.tres" % resource)
		Globals.ADDITIONAL_TOON_PATHS.append(character_path)
